/*
 * Copyright Amazon.com, Inc. or its affiliates.
 * All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific
 * language governing permissions and limitations under the License.
 */
package com.aws.carddemo.dto.response;

import java.time.LocalDateTime;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * Login Response DTO for authentication operations.
 * 
 * <p>This class represents the response returned from the POST /api/v1/auth/login endpoint
 * after successful user authentication. It replaces the COBOL/CICS COSGN00.bms screen
 * navigation with a stateless JWT-based authentication response.</p>
 * 
 * <p><b>Migration from COBOL:</b></p>
 * <ul>
 *   <li>Migrated from: app/bms/COSGN00.bms (login screen)</li>
 *   <li>User data from: app/cpy/CSUSR01Y.cpy (SEC-USER-DATA structure)</li>
 *   <li>Session context from: app/cpy/COCOM01Y.cpy (CARDDEMO-COMMAREA structure)</li>
 * </ul>
 * 
 * <p><b>COBOL to Java Field Mapping:</b></p>
 * <ul>
 *   <li>SEC-USR-ID (PIC X(08)) → username (String)</li>
 *   <li>SEC-USR-FNAME (PIC X(20)) → firstName (String)</li>
 *   <li>SEC-USR-LNAME (PIC X(20)) → lastName (String)</li>
 *   <li>SEC-USR-TYPE (PIC X(01)) → userType (String: 'A' for Admin, 'R' for Regular user)</li>
 *   <li>CDEMO-USER-ID (PIC X(08)) → username (String)</li>
 *   <li>CDEMO-USER-TYPE (PIC X(01)) → userType (String)</li>
 *   <li>EXEC CICS XCTL to COMEN01C/COADM01C → JWT token in JSON response</li>
 *   <li>COMMAREA session state → JWT claims encoded in accessToken</li>
 * </ul>
 * 
 * <p><b>Security Implementation:</b></p>
 * <ul>
 *   <li>Replaces RACF mainframe security with JWT-based authentication</li>
 *   <li>Replaces CICS session management with stateless token authentication</li>
 *   <li>Supports Bearer token authentication scheme for subsequent API requests</li>
 *   <li>Token expiration configurable (default 1 hour per security requirements)</li>
 *   <li>User password (SEC-USR-PWD) is NEVER included in response (security best practice)</li>
 *   <li>All sensitive data excluded from JSON serialization and logging</li>
 * </ul>
 * 
 * <p><b>Response Structure:</b></p>
 * <pre>
 * {
 *   "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
 *   "tokenType": "Bearer",
 *   "expiresIn": 3600000,
 *   "expiresAt": "2024-01-15T10:30:00",
 *   "userId": 12345,
 *   "username": "Z390USER",
 *   "firstName": "John",
 *   "lastName": "Doe",
 *   "userType": "A",
 *   "roles": ["ROLE_USER", "ROLE_ADMIN"]
 * }
 * </pre>
 * 
 * <p><b>Usage Example:</b></p>
 * <pre>
 * LoginResponse response = LoginResponse.builder()
 *     .accessToken(jwtToken)
 *     .tokenType("Bearer")
 *     .expiresIn(3600000L)
 *     .expiresAt(LocalDateTime.now().plusHours(1))
 *     .userId(user.getId())
 *     .username(user.getUsername())
 *     .firstName(user.getFirstName())
 *     .lastName(user.getLastName())
 *     .userType(user.getUserType())
 *     .roles(List.of("ROLE_USER", "ROLE_ADMIN"))
 *     .build();
 * </pre>
 * 
 * @see com.aws.carddemo.service.AuthenticationService
 * @see com.aws.carddemo.controller.AuthController
 * @see com.aws.carddemo.security.JwtTokenProvider
 * @since 1.0.0
 * @author AWS CardDemo Modernization Team
 */
@Getter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class LoginResponse {

    /**
     * JWT access token for authenticating subsequent API requests.
     * 
     * <p>This token contains encoded claims including user ID, username, user type,
     * and roles. It replaces the CICS COMMAREA session state from COCOM01Y.cpy
     * (CDEMO-USER-ID, CDEMO-USER-TYPE) with stateless JWT authentication.</p>
     * 
     * <p>The token is generated by JwtTokenProvider after successful password
     * validation with BCrypt, replacing COBOL plain-text password comparison
     * from COSGN00C.cbl with secure cryptographic hashing.</p>
     * 
     * <p><b>COBOL Context:</b> Replaces EXEC CICS XCTL navigation to COMEN01C
     * (main menu) or COADM01C (admin menu) based on SEC-USR-TYPE value.</p>
     * 
     * @see com.aws.carddemo.security.JwtTokenProvider#generateToken
     */
    @JsonProperty("accessToken")
    private String accessToken;

    /**
     * Token type for Authorization header format.
     * 
     * <p>Always returns "Bearer" to indicate Bearer token authentication scheme.
     * Client applications must include this token in HTTP requests using the
     * Authorization header: <code>Authorization: Bearer {accessToken}</code></p>
     * 
     * <p><b>COBOL Context:</b> No direct equivalent in COBOL. This is a REST API
     * standard for stateless authentication, replacing CICS session-based security.</p>
     */
    @JsonProperty("tokenType")
    @Builder.Default
    private String tokenType = "Bearer";

    /**
     * Token validity duration in milliseconds.
     * 
     * <p>Represents the number of milliseconds until token expiration from the
     * time of issuance. Default is 3600000 milliseconds (1 hour) per PCI-DSS
     * compliance requirements for session timeout.</p>
     * 
     * <p>Clients can use this value to refresh tokens before expiration or
     * prompt users to re-authenticate.</p>
     * 
     * <p><b>COBOL Context:</b> Replaces CICS transaction timeout (ICVTSD value).
     * COBOL applications relied on CICS automatic timeout, whereas REST APIs
     * require explicit token expiration management.</p>
     */
    @JsonProperty("expiresIn")
    private Long expiresIn;

    /**
     * Absolute expiration timestamp of the JWT token.
     * 
     * <p>ISO 8601 formatted date-time indicating when the token will expire.
     * This provides an absolute expiration time for client-side validation
     * and token refresh logic.</p>
     * 
     * <p>Format: "yyyy-MM-dd'T'HH:mm:ss" (e.g., "2024-01-15T10:30:00")</p>
     * 
     * <p><b>COBOL Context:</b> Replaces CICS transaction expiration logic.
     * COBOL programs used FUNCTION CURRENT-DATE for time tracking, replaced
     * with Java 8+ LocalDateTime for immutable, timezone-agnostic handling.</p>
     */
    @JsonProperty("expiresAt")
    private LocalDateTime expiresAt;

    /**
     * Unique numeric identifier for the authenticated user.
     * 
     * <p>This is the primary key from the USER table, derived from the
     * User entity ID after successful authentication.</p>
     * 
     * <p><b>COBOL Context:</b> Maps to database sequence-generated ID for the
     * USRSEC file record. COBOL used SEC-USR-ID as the primary identifier
     * (character-based), while Java uses a surrogate numeric key.</p>
     */
    @JsonProperty("userId")
    private Long userId;

    /**
     * User login identifier (username).
     * 
     * <p>Corresponds to SEC-USR-ID field from CSUSR01Y.cpy (PIC X(08)).
     * This is the unique username used for login authentication.</p>
     * 
     * <p>Maximum length: 8 characters (preserved from COBOL PIC X(08)).</p>
     * 
     * <p><b>COBOL Context:</b> Maps to SEC-USR-ID in SEC-USER-DATA structure
     * and CDEMO-USER-ID in CARDDEMO-COMMAREA structure from COCOM01Y.cpy.</p>
     * 
     * @see app/cpy/CSUSR01Y.cpy SEC-USR-ID
     * @see app/cpy/COCOM01Y.cpy CDEMO-USER-ID
     */
    @JsonProperty("username")
    private String username;

    /**
     * User's first name.
     * 
     * <p>Corresponds to SEC-USR-FNAME field from CSUSR01Y.cpy (PIC X(20)).</p>
     * 
     * <p>Maximum length: 20 characters (preserved from COBOL PIC X(20)).</p>
     * 
     * <p><b>COBOL Context:</b> Maps to SEC-USR-FNAME in SEC-USER-DATA structure.
     * Used for display purposes in COBOL screens and now provided in JSON
     * response for client-side UI rendering.</p>
     * 
     * @see app/cpy/CSUSR01Y.cpy SEC-USR-FNAME
     */
    @JsonProperty("firstName")
    private String firstName;

    /**
     * User's last name.
     * 
     * <p>Corresponds to SEC-USR-LNAME field from CSUSR01Y.cpy (PIC X(20)).</p>
     * 
     * <p>Maximum length: 20 characters (preserved from COBOL PIC X(20)).</p>
     * 
     * <p><b>COBOL Context:</b> Maps to SEC-USR-LNAME in SEC-USER-DATA structure.
     * Used for display purposes in COBOL screens and now provided in JSON
     * response for client-side UI rendering.</p>
     * 
     * @see app/cpy/CSUSR01Y.cpy SEC-USR-LNAME
     */
    @JsonProperty("lastName")
    private String lastName;

    /**
     * User type classification code.
     * 
     * <p>Corresponds to SEC-USR-TYPE field from CSUSR01Y.cpy (PIC X(01))
     * and CDEMO-USER-TYPE from COCOM01Y.cpy (PIC X(01)).</p>
     * 
     * <p><b>Valid values:</b></p>
     * <ul>
     *   <li>'A' - Administrator user (CDEMO-USRTYP-ADMIN in COBOL)</li>
     *   <li>'R' - Regular user (CDEMO-USRTYP-USER in COBOL, stored as 'U' internally)</li>
     * </ul>
     * 
     * <p><b>COBOL Context:</b> Maps to SEC-USR-TYPE and CDEMO-USER-TYPE with
     * 88-level condition names: CDEMO-USRTYP-ADMIN (VALUE 'A') and
     * CDEMO-USRTYP-USER (VALUE 'U'). The Java implementation uses 'R' for
     * regular users to match external API conventions.</p>
     * 
     * @see app/cpy/CSUSR01Y.cpy SEC-USR-TYPE
     * @see app/cpy/COCOM01Y.cpy CDEMO-USER-TYPE
     */
    @JsonProperty("userType")
    private String userType;

    /**
     * List of Spring Security role names assigned to the user.
     * 
     * <p>Contains role identifiers used for role-based access control (RBAC)
     * in Spring Security. Roles are derived from the userType field:</p>
     * <ul>
     *   <li>userType = 'A' → roles = ["ROLE_USER", "ROLE_ADMIN"]</li>
     *   <li>userType = 'R' → roles = ["ROLE_USER"]</li>
     * </ul>
     * 
     * <p><b>Usage:</b> These roles are used in @PreAuthorize annotations to
     * restrict access to admin endpoints. For example, DELETE /api/v1/admin/users/{id}
     * requires ROLE_ADMIN, which is only granted to users with userType 'A'.</p>
     * 
     * <p><b>COBOL Context:</b> Replaces COBOL 88-level condition names
     * CDEMO-USRTYP-ADMIN and CDEMO-USRTYP-USER from COCOM01Y.cpy. COBOL programs
     * used IF CDEMO-USRTYP-ADMIN checks to control menu options and program
     * access, replaced with Spring Security role-based method security.</p>
     * 
     * <p>The roles list enables client-side UI rendering decisions (e.g.,
     * showing/hiding admin menu options) and server-side authorization.</p>
     * 
     * @see com.aws.carddemo.config.SecurityConfig
     * @see app/cpy/COCOM01Y.cpy CDEMO-USER-TYPE 88-levels
     */
    @JsonProperty("roles")
    private List<String> roles;
}
