package com.aws.carddemo.model;

import java.io.Serializable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Composite primary key class for DisclosureGroup entity.
 * 
 * <p>This class represents the composite primary key for the DisclosureGroup entity,
 * consisting of three fields that uniquely identify a disclosure group interest rate
 * configuration. It is used with the @IdClass annotation on the DisclosureGroup entity
 * to enable JPA composite key mapping.</p>
 * 
 * <p>Migrated from: app/cpy/CVTRA02Y.cpy (DIS-GROUP-KEY structure)</p>
 * 
 * <p>Original COBOL structure:
 * <pre>
 * 05  DIS-GROUP-KEY.
 *    10 DIS-ACCT-GROUP-ID    PIC X(10).
 *    10 DIS-TRAN-TYPE-CD     PIC X(02).
 *    10 DIS-TRAN-CAT-CD      PIC 9(04).
 * </pre>
 * </p>
 * 
 * <p>JPA Composite Key Requirements:</p>
 * <ul>
 *   <li>Must implement Serializable interface</li>
 *   <li>Must override equals() and hashCode() methods</li>
 *   <li>Must have a no-argument constructor</li>
 *   <li>All fields must match the @Id annotated fields in the entity</li>
 * </ul>
 * 
 * <p>Usage Example:</p>
 * <pre>
 * DisclosureGroupId id = new DisclosureGroupId("GROUP01", "01", "0001");
 * Optional&lt;DisclosureGroup&gt; group = disclosureGroupRepository.findById(id);
 * </pre>
 * 
 * @see com.aws.carddemo.model.DisclosureGroup
 * @see javax.persistence.IdClass
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class DisclosureGroupId implements Serializable {

    /**
     * Serial version UID for serialization compatibility.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Account group identifier.
     * 
     * <p>Corresponds to DIS-ACCT-GROUP-ID PIC X(10) in CVTRA02Y.cpy.</p>
     * <p>Categorizes accounts into different groups for interest rate determination.</p>
     * 
     * <p>Example values: "STANDARD", "PREMIUM", "REWARDS"</p>
     */
    private String accountGroupId;

    /**
     * Transaction type code.
     * 
     * <p>Corresponds to DIS-TRAN-TYPE-CD PIC X(02) in CVTRA02Y.cpy.</p>
     * <p>Identifies the type of transaction for interest rate calculation.</p>
     * 
     * <p>Example values: "01" (Purchase), "02" (Cash Advance), "03" (Balance Transfer)</p>
     */
    private String transactionTypeCode;

    /**
     * Transaction category code.
     * 
     * <p>Corresponds to DIS-TRAN-CAT-CD PIC 9(04) in CVTRA02Y.cpy.</p>
     * <p>Provides granular categorization within a transaction type for specific interest rates.</p>
     * 
     * <p>Example values: "0001" (Retail), "0002" (Grocery), "0003" (Gas)</p>
     */
    private String transactionCategoryCode;

    /**
     * Compares this composite key with another object for equality.
     * 
     * <p>Two DisclosureGroupId instances are considered equal if all three key fields
     * (accountGroupId, transactionTypeCode, transactionCategoryCode) are equal.</p>
     * 
     * <p>This method is automatically generated by Lombok @Data annotation and uses
     * Objects.equals() for null-safe comparison of all fields.</p>
     * 
     * @param o the object to compare with
     * @return true if the objects are equal, false otherwise
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        DisclosureGroupId that = (DisclosureGroupId) o;
        return java.util.Objects.equals(accountGroupId, that.accountGroupId) &&
               java.util.Objects.equals(transactionTypeCode, that.transactionTypeCode) &&
               java.util.Objects.equals(transactionCategoryCode, that.transactionCategoryCode);
    }

    /**
     * Generates a hash code for this composite key.
     * 
     * <p>The hash code is computed from all three key fields (accountGroupId,
     * transactionTypeCode, transactionCategoryCode) using Objects.hash().</p>
     * 
     * <p>This method is automatically generated by Lombok @Data annotation and ensures
     * consistent hash code generation for composite key identity management in JPA.</p>
     * 
     * @return the hash code value for this composite key
     */
    @Override
    public int hashCode() {
        return java.util.Objects.hash(accountGroupId, transactionTypeCode, transactionCategoryCode);
    }
}
