package com.aws.carddemo.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;

/**
 * Composite primary key class for TransactionCategory entity.
 * 
 * <p>This class implements the JPA @IdClass pattern for composite primary keys,
 * representing the two-column primary key (transaction_type_code, category_code)
 * from the TRAN_CAT_RECORD data structure.</p>
 * 
 * <p>Migrated from: app/cpy/CVTRA04Y.cpy (TRAN-CAT-KEY structure)</p>
 * 
 * <p>COBOL Structure Mapping:</p>
 * <pre>
 * 05  TRAN-CAT-KEY.
 *    10  TRAN-TYPE-CD    PIC X(02)  -> transactionTypeCode (String, 2 chars)
 *    10  TRAN-CAT-CD     PIC 9(04)  -> categoryCode (String, 4 chars)
 * </pre>
 * 
 * <p>JPA Specification Requirements:</p>
 * <ul>
 *   <li>Must implement Serializable interface</li>
 *   <li>Must have public no-argument constructor</li>
 *   <li>Must override equals() and hashCode() methods</li>
 *   <li>All fields must be public or have public accessor methods</li>
 * </ul>
 * 
 * <p>Usage Example:</p>
 * <pre>
 * TransactionCategoryId id = new TransactionCategoryId("01", "0001");
 * Optional&lt;TransactionCategory&gt; category = transactionCategoryRepository.findById(id);
 * </pre>
 * 
 * @see com.aws.carddemo.model.TransactionCategory
 * @see javax.persistence.IdClass
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class TransactionCategoryId implements Serializable {

    /**
     * Serial version UID for serialization compatibility.
     * Required by Serializable interface.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Transaction type code.
     * 
     * <p>Maps to TRAN-TYPE-CD PIC X(02) from COBOL copybook.</p>
     * <p>Represents the transaction type (e.g., "01" for Purchase, "02" for Return).</p>
     * <p>Maximum length: 2 characters</p>
     */
    private String transactionTypeCode;

    /**
     * Transaction category code.
     * 
     * <p>Maps to TRAN-CAT-CD PIC 9(04) from COBOL copybook.</p>
     * <p>Represents the category within a transaction type (e.g., "0001" for Retail).</p>
     * <p>Maximum length: 4 characters (numeric)</p>
     */
    private String categoryCode;

    /**
     * Compares this composite key with another object for equality.
     * 
     * <p>Two TransactionCategoryId objects are considered equal if both
     * transactionTypeCode and categoryCode fields are equal.</p>
     * 
     * <p>This method is automatically generated by Lombok's @Data annotation
     * and uses Objects.equals() for null-safe comparison.</p>
     * 
     * @param o the object to compare with
     * @return true if the objects are equal, false otherwise
     */
    // equals() method generated by @Data annotation

    /**
     * Returns a hash code value for this composite key.
     * 
     * <p>The hash code is computed based on both transactionTypeCode and
     * categoryCode fields using Objects.hash().</p>
     * 
     * <p>This method is automatically generated by Lombok's @Data annotation
     * and ensures consistent hash code generation for use in hash-based
     * collections (HashMap, HashSet, etc.).</p>
     * 
     * @return hash code value for this composite key
     */
    // hashCode() method generated by @Data annotation

    /**
     * Returns a string representation of this composite key.
     * 
     * <p>The string representation includes both field names and values,
     * useful for debugging and logging.</p>
     * 
     * <p>This method is automatically generated by Lombok's @Data annotation.</p>
     * 
     * @return string representation of this composite key
     */
    // toString() method generated by @Data annotation
}
