package com.aws.carddemo.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;

/**
 * Composite primary key class for TransactionCategoryBalance entity.
 * <p>
 * Migrated from: app/cpy/CVTRA01Y.cpy (TRAN-CAT-KEY structure)
 * <p>
 * This class implements the JPA @IdClass pattern for composite primary keys consisting of three fields:
 * accountId, transactionTypeCode, and transactionCategoryCode. Per JPA specification requirements,
 * this class implements Serializable and provides proper equals() and hashCode() implementations
 * (generated by Lombok @Data annotation) for composite key identity comparison.
 * <p>
 * The composite key enables tracking of transaction category balances at the granular level of
 * account + transaction type + transaction category, matching the COBOL TRAN-CAT-KEY structure:
 * - TRANCAT-ACCT-ID (PIC 9(11)) → accountId (Long)
 * - TRANCAT-TYPE-CD (PIC X(02)) → transactionTypeCode (String, 2 chars)
 * - TRANCAT-CD (PIC 9(04)) → transactionCategoryCode (String, 4 chars)
 * <p>
 * Usage example:
 * <pre>
 * TransactionCategoryBalanceId id = new TransactionCategoryBalanceId(1L, "01", "0001");
 * Optional&lt;TransactionCategoryBalance&gt; balance = repository.findById(id);
 * </pre>
 *
 * @see TransactionCategoryBalance
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class TransactionCategoryBalanceId implements Serializable {

    /**
     * Serial version UID for Serializable interface compliance.
     * Required for JPA composite key serialization and deserialization.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Account identifier portion of the composite key.
     * <p>
     * Migrated from: TRANCAT-ACCT-ID PIC 9(11) in CVTRA01Y.cpy
     * <p>
     * Represents the 11-digit account number that owns the transaction category balance.
     * Must match the accountId field annotated with @Id in TransactionCategoryBalance entity.
     */
    private Long accountId;

    /**
     * Transaction type code portion of the composite key.
     * <p>
     * Migrated from: TRANCAT-TYPE-CD PIC X(02) in CVTRA01Y.cpy
     * <p>
     * Two-character code identifying the transaction type (e.g., "01" for purchases, "02" for payments).
     * Must match the transactionTypeCode field annotated with @Id in TransactionCategoryBalance entity.
     * Valid values are defined in the TRANSACTION_TYPE reference table.
     */
    private String transactionTypeCode;

    /**
     * Transaction category code portion of the composite key.
     * <p>
     * Migrated from: TRANCAT-CD PIC 9(04) in CVTRA01Y.cpy
     * <p>
     * Four-character code identifying the transaction category (e.g., "0001" for groceries, "0002" for gas).
     * Must match the transactionCategoryCode field annotated with @Id in TransactionCategoryBalance entity.
     * Valid values are defined in the TRANSACTION_CATEGORY reference table.
     */
    private String transactionCategoryCode;

    // Note: equals() and hashCode() are automatically generated by Lombok @Data annotation.
    // These methods compare all three fields (accountId, transactionTypeCode, transactionCategoryCode)
    // using null-safe comparison logic, ensuring proper composite key identity semantics.
    // Implementation uses Objects.equals() for null-safe field comparison and Objects.hash()
    // for consistent hash code generation across all three key fields.
}
